version: '3.8'

services:
  service-discovery:
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    container_name: service-discovery
    restart: always
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-server:
    build:
      context: ./config
      dockerfile: Dockerfile
    container_name: config-server
    restart: always
    expose:
      - "8888"
    depends_on:
      - service-discovery
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
    ports:
      - "8000:8000"
    depends_on:
      - service-discovery
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    environment:
      - spring.cloud.config.uri=http://config-server:8888
      - eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka
    depends_on:
      - service-discovery
      - config-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge